POST http://localhost:8080/api/v1/vm
Content-Type: application/json

{
  "name": "kubernix-2",
  "iso_image": "/home/ramanuj/Downloads/ubuntu-20.04.6-live-server-amd64.iso",
  "memory_mb": 4096,
  "cpus": 2,
  "disk_size_gb": 20
}
